feat: add checks in scripts

diff --git a/models/bpmn-origin/run b/models/bpmn-origin/run
--- a/models/bpmn-origin/run
+++ b/models/bpmn-origin/run
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+if ! which fbpmn &> /dev/null; then
+  echo "fbpmn is not found in the PATH, please install it"
+  exit 1
+fi
+
 for f in `ls src/*.bpmn`
 do
   ff=`basename $f`
diff --git a/scripts/fbpmn-check b/scripts/fbpmn-check
--- a/scripts/fbpmn-check
+++ b/scripts/fbpmn-check
@@ -23,6 +23,16 @@ if [ $# -ne 1 ]; then
   exit 1
 fi
 
+if ! which fbpmn &> /dev/null; then
+  echo "fbpmn is not found in the PATH, please install it"
+  exit 1
+fi
+
+if ! which java &> /dev/null; then
+  echo "java is not found in the PATH, please install it"
+  exit 1
+fi
+
 if [ -z $FBPMN_HOME ]; then
         echo FBPMN_HOME is not set; exit 1
 fi
